# Tarea Semana 2 (MIT OLL)

In [2]:
import numpy as np

In [3]:
# funciones auxiliares

def rv(value_list):
    return np.array([value_list])

def tp(A):
    return np.transpose(A)

def cv(value_list):
    return tp(rv(value_list))

In [82]:
def actualiza(theta,x,y,origen = True):
    if origen:
        if y * (theta.T @ x) <= 0:
            return theta + y*x
        else:
            print("no es necesario actualizar")
            return theta

def verifica(theta,X,Y,origen= True):
    if origen:
        return np.sign(theta.T @ X) == Y.T

In [83]:
X = np.array([[1,-1],[0,1],[-1.5,-1]]).T
Y = np.array([[1],[-1],[1]])

In [84]:
# COmenzar con X_1

x = X[:,0:1]
theta = cv([0,0])
y = Y[0,0]
theta = actualiza(theta,x,y)
theta

array([[ 1.],
       [-1.]])

In [85]:
verifica(theta,X,Y)

array([[ True,  True, False]])

In [86]:
x = X[:,1:2]
y = Y[1,0]
theta = actualiza(theta,x,y)

no es necesario actualizar


In [87]:
verifica(theta,X,Y)

array([[ True,  True, False]])

In [88]:
x = X[:,2:3]
y = Y[2,0]
theta = actualiza(theta,x,y)

In [89]:
theta

array([[-0.5],
       [-2. ]])

In [90]:
verifica(theta,X,Y)

array([[ True,  True,  True]])

In [93]:
# COmenzar con x^2

x = X[:,1:2]
y = Y[1,0]
theta = cv([0,0])
theta = actualiza(theta,x,y)
theta

array([[ 0.],
       [-1.]])

In [94]:
verifica(theta,X,Y)

array([[ True,  True,  True]])

## 1.2a)

In [95]:
# 1.2a)
X = np.array([[1,-1],[0,1],[-10,-1]]).T
Y = np.array([[1],[-1],[1]])


In [96]:
# COmenzar con X_1

x = X[:,0:1]
theta = cv([0,0])
y = Y[0,0]
theta = actualiza(theta,x,y)
theta

array([[ 1],
       [-1]])

In [97]:
verifica(theta,X,Y)

array([[ True,  True, False]])

In [98]:
x = X[:,1:2]
y = Y[1,0]
theta = actualiza(theta,x,y)
theta

no es necesario actualizar


array([[ 1],
       [-1]])

In [99]:
x = X[:,2:3]
y = Y[2,0]
theta = actualiza(theta,x,y)
theta

array([[-9],
       [-2]])

In [100]:
verifica(theta,X,Y)

array([[False,  True,  True]])

In [101]:
x = X[:,0:1]
y = Y[0,0]
theta = actualiza(theta,x,y)
theta

array([[-8],
       [-3]])

In [102]:
verifica(theta,X,Y)

array([[False,  True,  True]])

In [103]:
x = X[:,1:2]
y = Y[1,0]
theta = actualiza(theta,x,y)
theta

no es necesario actualizar


array([[-8],
       [-3]])

In [104]:
x = X[:,2:3]
y = Y[2,0]
theta = actualiza(theta,x,y)
theta

no es necesario actualizar


array([[-8],
       [-3]])

In [105]:
x = X[:,0:1]
y = Y[0,0]
theta = actualiza(theta,x,y)
theta

array([[-7],
       [-4]])

In [106]:
verifica(theta,X,Y)

array([[False,  True,  True]])

In [107]:
x = X[:,1:2]
y = Y[1,0]
theta = actualiza(theta,x,y)
theta

no es necesario actualizar


array([[-7],
       [-4]])

In [108]:
x = X[:,2:3]
y = Y[2,0]
theta = actualiza(theta,x,y)
theta

no es necesario actualizar


array([[-7],
       [-4]])

In [109]:
x = X[:,0:1]
y = Y[0,0]
theta = actualiza(theta,x,y)
theta

array([[-6],
       [-5]])

In [110]:
verifica(theta,X,Y)

array([[False,  True,  True]])

In [111]:
x = X[:,1:2]
y = Y[1,0]
theta = actualiza(theta,x,y)
theta

no es necesario actualizar


array([[-6],
       [-5]])

In [112]:
x = X[:,2:3]
y = Y[2,0]
theta = actualiza(theta,x,y)
theta

no es necesario actualizar


array([[-6],
       [-5]])

In [113]:
x = X[:,0:1]
y = Y[0,0]
theta = actualiza(theta,x,y)
theta

array([[-5],
       [-6]])

In [114]:
verifica(theta,X,Y)

array([[ True,  True,  True]])

## Problemas 7 a 10 

Los problemas 7 a 10 [son programas en colab](https://colab.research.google.com/drive/1kIWGi2TEZ0Agd_qQt1KiD2uZw_5AJFHT)

